include:
  - project: emfollow/gitlab-ci-templates
    file: lint.yml
  - project: emfollow/gitlab-ci-templates
    file: sccb.yml

# Build source distribution
sdist:
  image: python
  stage: build
  script:
    - python setup.py sdist
    - mv dist/* .
  artifacts:
    paths:
      - '*.tar.gz'

# Build binary distribution
bdist:
  image: python
  stage: build
  script:
    - python setup.py bdist_wheel
    - mv dist/* .
  artifacts:
    paths:
      - '*.whl'

.test: &test:
  image: python:slim
  stage: test
  before_script:  # Install robot keytab for integration tests
    - apt-get update && apt-get install -y curl krb5-user xsltproc
    # Decode base64-encoded keytab
    - echo "${ROBOT_KEYTAB}" | base64 -d | install -m 0600 /dev/stdin keytab
    # Read principal from first entry in keytab
    - PRINCIPAL=$(klist -k keytab | head -n 4 | tail -n 1 | sed -E 's/^.* +//')
    # Create X.509 certificate
    - kinit $PRINCIPAL -k -t keytab
    - rm keytab
    - ./ligo-proxy-init -k
  script:
    - pip install pytest-cov
    - python setup.py test --addopts='--cov --cov-report=html --cov-report=term --junit-xml=junit.xml -vv'
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: junit.xml

test/3.5:
  image: python:3.5-slim
  <<: *test

test/3.6:
  image: python:3.6-slim
  <<: *test

test/3.7:
  image: python:3.7-slim
  <<: *test

test/3.8:
  image: python:3.8-slim
  <<: *test

pages:
  stage: deploy
  script:
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  dependencies:
    - test/3.8

# SCCB request
sccb:
  stage: deploy

# Upload package to PyPI
pypi:
  stage: deploy
  image: python:slim
  script:
    - pip install twine
    - twine upload *.tar.* *.whl
  dependencies:
    - sdist
    - bdist
  only:
    - tags@emfollow/gracedb-sdk
