include:
  - project: emfollow/gitlab-ci-templates
    file: lint.yml

test:
  image: python
  stage: test
  before_script:  # Install robot keytab for integration tests
    - git clone --depth 1 https://git.ligo.org/Auth/Shibboleth-SP/ligo-proxy-utils
    - apt-get update && apt-get install -y --no-install-recommends krb5-user
    # Decode base64-encoded keytab
    - echo "${ROBOT_KEYTAB}" | base64 -d | install -m 0600 /dev/stdin keytab
    # Read principal from first entry in keytab
    - PRINCIPAL=$(klist -k keytab | head -n 4 | tail -n 1 | sed -E 's/^.* +//')
    # Create X.509 certificate
    - kinit $PRINCIPAL -k -t keytab
    - rm keytab
    - ligo-proxy-utils/ligo-proxy-init -k -p
  script:
    - pip install pytest-cov -r test-requirements.txt
    - python setup.py test --addopts='--cov --cov-report=html --cov-report=term --junit-xml=junit.xml -vv'
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      junit: junit.xml

pages:
  stage: deploy
  script:
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  dependencies:
    - test
